export { default as Play } from './play.svg.svelte'
export { default as Pause } from './pause.svg.svelte'
export { default as Stop } from './stop.svg.svelte'
export { default as Disc } from './disc.svg.svelte'
export { default as Gear } from './gear.svg.svelte'
export { default as Loading } from './loading.svg.svelte'
export { default as Hourglass } from './hourglass.svg.svelte'
export { default as Mute } from './mute.svg.svelte'
export { default as Volume } from './volume.svg.svelte'
export { default as CircleX } from './circle-x.svg.svelte'
export { default as Bug } from './bug.svg.svelte'
export { default as CircleCheck } from './circle-check.svg.svelte'
export { default as Menu } from './menu.svg.svelte'
// Social
export { default as SocialX } from './social-x.svg.svelte'
export { default as SocialTelegram } from './social-telegram.svg.svelte'
export { default as SocialYoutube } from './social-youtube.svg.svelte'
export { default as SocialInstagram } from './social-instagram.svg.svelte'
